name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(echo $JAVA_HOME)" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'


      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Run UI Tests"
        uses: vgaidarji/android-github-actions-emulator@v1.0.1


      - name: Run unit tests
        run: ./gradlew Test
        continue-on-error: true # Allow the workflow to continue even if some tests fail

      - name: Run ui tests
        run: ./gradlew connectedAndroidTest
        continue-on-error: true # Allow the workflow to continue even if some tests fail


      - name: Upload Test Results
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: app/build/reports/tests

